[book]
authors = ["Typewritergoblin"]
language = "en"
src = "src"
title = "Eberron 5.5ish Setting"

[output.html]
site-url = "/eberronAdvancedMdBook/"
default-theme = "navy"

[output.html.fold]
enable = true
level = 0